### ISSUE TITLE
Bug: Maximizing button doesn't work when clicking on the icon

### ISSUE THREAD

**Issue by ThisWillDoIt** [chingucoding/UWP-Resources-Gallery#14]
When the app runs in full screen mode you can press the button next to the title to minimize the app to the little window that stays on top.  
If you want to report that you have to click the button again but it only works if you hit the area inbetwen the icon and the actual edge of the icon. Clicking the icon itself does nothing.  
If the small window is resized the icon itself become clickable as intended.

**Comment by chingucoding** [comment]
Thank you for the bug report! In the next release, the button will be on the left to prevent it from being unclickable on smaller sizes.
