### ISSUE TITLE
Automatically focus search textbox when opening a section

### ISSUE THREAD

**Issue by MarcAnt01** [chingucoding/UWP-Resources-Gallery#28]
I often happen to search contents rather than finding them manually, so I think that the focus should be on search textbox

**Comment by chingucoding** [comment]
Thank you for the suggestion, this definitely is a good idea. I've published the new version (1.2.3.0) to the app store, and it should be available in the store in the next few hours/days.

**Comment by MarcAnt01** [comment]
Thank you for the app, I save me a lot of time using it when I deal with icon assets

**Comment by chingucoding** [comment]
I am happy that you like it, and it helps you!

PS: The update is available on the store now.
