### ISSUE TITLE
Start page looks a bit empty

### ISSUE THREAD

**Issue by MarcAnt01** [chingucoding/UWP-Resources-Gallery#30]
I would suggest you to add a picture like the one of XAML Controls Gallery to make it look less empty
![image](https://user-images.githubusercontent.com/43090263/89777505-22504d80-db0c-11ea-8d3a-e68690a85c53.png)

**Comment by chingucoding** [comment]
I agree with you, the start page does look quite empty. However I am not entirely sure if adding an image just for the sake of it is the best solution here.
