### ISSUE TITLE
RGB color values for Systembrushes

### ISSUE THREAD

**Issue by maxkatz6** [chingucoding/UWP-Resources-Gallery#32]
Hi!
Thanks for the application!
I saw another issue for Systemcolors - https://github.com/chingucoding/UWP-Resources-Gallery/issues/4
And I think same information may be convenient for Systembrushes page.

**Comment by chingucoding** [comment]
Hi @maxkatz6 ,
Thank you for using my app!

I really like this idea, this will definitely be added to the app. If you by any chance want to contribute this, feel free to let me know, otherwise I would work on this this week.

**Comment by chingucoding** [comment]
The newest version (1.3.1) was just released to the store which adds the hex codes for the SystemBrushes page.
