### ISSUE TITLE
Suggestion: Display calculated Alpha/Hex/RGB values for each resource

### ISSUE THREAD

**Issue by mdtauk** [chingucoding/UWP-Resources-Gallery#4]
Something for designers and those making mock ups, would be to display the actual alpha RGB and Hex values for each of the colours.

**Comment by chingucoding** [comment]
I agree, great suggestion! What "formats" would you deem good beside Hex (i.e. #FFFFFFFF)?

**Comment by mdtauk** [comment]
Hex is the good catch all, but should it be **AA RR GG BB** or **RR GG BB** with an **Alpha** listed separately?

I have listed these things for various proposals and I tend to alternate.

![image](https://user-images.githubusercontent.com/7389110/72190392-525d3400-33f7-11ea-9dc8-75dda9dc8fc2.png)  
![image](https://user-images.githubusercontent.com/7389110/72190453-7f114b80-33f7-11ea-9eca-41f806e4b8d8.png)

**Comment by chingucoding** [comment]
I think for clarity it would be easier to always specify it as AARRGGBB, and not separate AA from RRGGBB. 
The next question would be to write it as "##AARRGGBB" or "#AA RR GG BB"?
I am leaning more towards the first one since this is accepted everywhere, while I am not quite if the second one would be simple to copy paste into apps (since it would have whitespaces in between).

What are your thoughts on this @mdtauk?

**Comment by mdtauk** [comment]
> I think for clarity it would be easier to always specify it as AARRGGBB, and not separate AA from RRGGBB.
> The next question would be to write it as "##AARRGGBB" or "#AA RR GG BB"?
> I am leaning more towards the first one since this is accepted everywhere, while I am not quite if the second one would be simple to copy paste into apps (since it would have whitespaces in between).
> 
> What are your thoughts on this @mdtauk?

I separate for display and readability, but your app may have a focus on coping and pasting.  Many apps do not include Alpha in their Hex inputs however, so that would be a reason for showing a separate Opacity

**Comment by chingucoding** [comment]
> Edit: You could include a Copy button beside the value, which puts it into the clipboard properly formatted, and display it in a more readable way?

Great idea! This seems like the best compromise between readability and usability.
