### ISSUE TITLE
Light and Dark Accent Color shades missing

### ISSUE THREAD

**Issue by mdtauk** [chingucoding/UWP-Resources-Gallery#7]
Light and Dark Accent Color shades are missing from the list.  Light 1,2,3 and Dark 1,2,3

**Comment by chingucoding** [comment]
There are probably more colors missing, however the documentation on this is not very clear. I have opened an issue on the respective documentation GitHub page:

https://github.com/MicrosoftDocs/windows-uwp/issues/2072

I think it may be better to wait until there is an actual complete list of system colors and see what colors are missing in addition to those 6 you mentioned.

</br></br>

In the mean time, if you want you can add those colors. To add colors one simply has to add the corresponding entries in the `SystemColors.json` file which you can find here:

https://github.com/chingucoding/UWP-Resources-Gallery/blob/master/src/ResourceModel/Assets/SystemColors.json

**Comment by mdtauk** [comment]
https://docs.microsoft.com/en-us/windows/uwp/design/style/color#accent-color-palette

- SystemAccentColorLight3
- SystemAccentColorLight2
- SystemAccentColorLight1

- SystemAccentColorDark1
- SystemAccentColorDark2
- SystemAccentColorDark3

**Comment by chingucoding** [comment]
I have added the missing colors now. If there are any other colors missing, feel free to create a new issue or reopen this one!
