### ISSUE TITLE
the colors aren't easy to recognize visually 

### ISSUE THREAD

**Issue by MuziburRahman** [chingucoding/UWP-Resources-Gallery#8]
This page in Microsoft Docs does a much better job:
https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/xaml-theme-resources#base
The `ItemTemplate` should be modified so that the ThemeResources are easy to detect.

**Comment by chingucoding** [comment]
Yes the docs do a pretty good job to show the colors.

> The ItemTemplate should be modified so that the ThemeResources are easy to detect.

What exactly do you mean by that? Would larger rectangles for the colors help or is there something else that might improve the visibility? (Note that there is different colored background in those boxes to highlight the fact that some colors are partially opaque)

**Comment by MuziburRahman** [comment]
larger rectangles for the colors will help

**Comment by MuziburRahman** [comment]
I also think the cell size of GridView for icons should be a little smaller.

**Comment by chingucoding** [comment]
> larger rectangles for the colors will help

I will look how i can improve that.

> I also think the cell size of GridView for icons should be a little smaller.

The reason for the size, is that some icon names are pretty long and I wanted to avoid having them break into two lines.

Thanks for your feedback!
